# Generated by Django 4.2.6 on 2023-10-18 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha',
        ),
    ]
